### ISSUE TITLE
Make spawning tools unbreakable on Archer

### ISSUE THREAD

**Issue by Arcsing** [StratusNetwork/Issues#151]
The iron blocks on the map will only give you already crafted armor pieces, so there's no way to make new tools when the ones you spawn with break. 

Also, it'd be good to add leaf decay or instead add shears to the spawn kit. The map is full of trees and punching leaves gets old real quick.

**Comment by BGMP** [comment]
I have decided to take the feedback and apply it to the map, since it makes sense that tools should be unbreakable because iron blocks don't give iron ingots, and that's also the reason why players aren't be able to craft shears.

I've added this features to the spawn kit. Thanks!

https://gitlab.com/stratus/maps/commit/2b25a5f54a04fafa758ba397ba1f92b2fbd3d4be
