### ISSUE TITLE
[Hemlock] Can place blocks at water portal exit

### ISSUE THREAD

**Issue by Marcono1234** [StratusNetwork/Issues#169]
On the map "Hemlock" you can place blocks at the exit position of the water portal, causing the teleported player to suffocate (at least on the blue side).

**Comment by BGMP** [comment]
I've seen this issue quite often in matches where some players block the portal exit in order to grind the teleported users. I find it really has potential to be absued, hence that I've created two regions that will prevent players from modifying at least a 3x3x3 cuboid around the teleport exits, among with marking the exits with each team's color stained clay to identify their purpose easily.

https://gitlab.com/stratus/maps/commit/2008cc25b6a7343017aa76afb280a1f1b6599a78
