### ISSUE TITLE
A New Day II Update

### ISSUE THREAD

**Issue by dcstarwars** [StratusNetwork/Issues#191]
I have updated my map, A New Day II, I have changed the wool attainment from pulling out of a chest to being spawned, as well as fixing the golden apple spawners as well.

https://www.dropbox.com/s/thcokzybzchhyek/A%20New%20Day%20II.zip?dl=0

**Comment by BGMP** [comment]
I've updated the map to version 1.1 with the files you've provided, yet I removed flowers being able to drop, and also fixed something I belive wasn't intentional:

![2018-02-07_03 45 07](https://user-images.githubusercontent.com/26081543/35902518-40816c2c-0bba-11e8-986b-5d594d1cfe9a.png)

Thanks for the update, it should be live on the server now!
