### ISSUE TITLE
Poor TPS on water drop

### ISSUE THREAD

**Issue by rafibaum** [StratusNetwork/Issues#285]
Observed on Limbo at least, not sure about other water drop maps. Basically TPS goes down the drain for whatever reason.

**Comment by mitchts** [comment]
Likey related to the number of fireworks that a set of each time the hills are captured. As the hills, especially the one right outside of spawn, are changing hands every second, that is going to be a lot of fireworks. I can completely hide the hills in order to disable the fireworks to see if that changes anything, but the downside to that is you won't see any capture messages in chat. You might not even see that as a downside, however.

**Comment by rafibaum** [comment]
Yeah I don't see that as a downside. I don't really think anybody sees value in the capture messages when there's so many of them. I'm not sure if fireworks cause server-side lag though. I imagine they could cause FPS issues, but what I was noticing was definitely a drop in TPS and I can't see from a performance perspective how fireworks would cause that.
