### ISSUE TITLE
Tetrad crashing issue

### ISSUE THREAD

**Issue by Matic0B** [StratusNetwork/Issues#90]
Hi, 
I have play a Tetrad game at 18:00:58 GMT+2 from eu proxy and a bug appends. 
Multiple peoples has taken wool at the same time and result a kick of each one has taken a wool.
Note : I don't see the wool in my inventory.
The player were using multiple versions from 1.8 to 1.11 (1.9.4 for me) so I don't think it has a link. 
I search on PGM source code(https://github.com/OvercastNetwork/ProjectAres/) to try understanding what appends at this moment.

Here is a link of each PlayerPickupEvent(seem to be the trigger) : https://github.com/OvercastNetwork/ProjectAres/search?utf8=%E2%9C%93&q=PlayerPickupItemEvent&type=
1) ToolRepairMatchModule.java(34) : Repair tools
2) EnvironmentControlListener.java(114) : Canceling default bukkit interaction to use PGM instead.
3) PGMListener.java(82) : Seems to be a temp fix for something.
4) EventFilterMatchModule.java(335) : Prevent player pickup items before the math start.
5) ViewInventoryMatchModule.java(198) : Process the event ???
6) ItemTransferListener.java(74) : Replace the cancel operation made by EnvironmentControlListener.java
7) GhostSquadronMatchModule.java(106) : Don't care it's ghost squandron

The two class ViewInventoryMatchModule.java(198) and ItemTransferListener.java(74) should generate the exception. Look at the console

~Dwopsky

*Sent to me by Dwopsky on Discord*

**Comment by victor-rsibillon** [comment]
Hi,
I think that isn't a plugin issue otherwise it will be a general problem and it will come on every map.
The problem comes from Tetrad Map ! Only a few people have this issue and they are **NOT** running 1.7 - 1.9

So I think, the problem may come from wools'NBT tags for client only. If it a server side problem the server will just crash.
The spawner generates a 'corrupted wool' and when the player picks up the wool the client cannot decipher/decode the wool tags.

A mojang fix with the pickup item has been released : 
- **Pick block moves items and removes their nbt** > https://bugs.mojang.com/browse/MC-79710

To fix the problem, maybe replace spawners or add wool chest.

_~Dwopsky_

**Comment by Palmidence** [comment]
@dwopsky I think it's better to move to chests for the CTW maps since they seem to be crashing players (Tetrad and Battle Ecliptica III come to mind). I would like some input about this, since if I change Tetrad it'd be necessary to change other maps.

As far as I know, Dynamo doesn't have any crashing. Could someone verify that for me that it works? I then might have a lead into what's going on.

**Comment by mitchts** [comment]
If Mojang resolved the issue and we just need to replace these corrupt wool spawners, then do that. Wool spawners are often a design choice, and changing that to a chest might have unintended effects on the gameplay.

**Comment by Palmidence** [comment]
@mitchiiii We'd need a list of maps with broken spawners. We can do that rather easily, or find an MCEdit filter to do it for us

**Comment by 2000thehecf1** [comment]
@Palmidence from the ones I've played and know it's only happening on Tetrad (which by the way is still in rotation) and Battle Ecliptica IV.V
